name: Code Style

on: [ push ]

jobs:
    php-cs-fixer:
        name: PHP CS Fixer
        runs-on: ubuntu-latest
        steps:
            -   name: Prepare github actions
                uses: actions/checkout@v2

            -   name: Run PHP CS Fixer
                uses: docker://oskarstark/php-cs-fixer-ga
                with:
                    args: --diff --dry-run
